### ISSUE TITLE
Unhandled rejection ReferenceError: merge is not defined

### ISSUE THREAD

**Issue by danielfeelfine** [bartve/disconnect#14]
I try to use ```addFolder``` method of *collection*, and recieve the error.

I think the mistake may be on the line 57 of [util.js](https://github.com/bartve/disconnect/blob/master/lib/util.js#L57).

**Comment by bartve** [comment]
Oops! the `merge` function used to be part of the `client` module. When I moved it to `util` I must have forgotten to update the recursive call. Will be fixed in the next update.

**Comment by bartve** [comment]
Never knew this was allowed http://stackoverflow.com/a/7065175
I'm at work now and no dev environment at home, so I hope this quick fix works.

**Comment by danielfeelfine** [comment]
Works fine for me :+1:
