### ISSUE TITLE
Search without a query for returns full index of vynils

### ISSUE THREAD

**Issue by danielfeelfine** [bartve/disconnect#15]
It can make a search without a query for receive the index of vynils?

The current search requires a query, and when empty (or undefined), returns or values ```""``` or ```Undefined``` in the title of vynils.

How I make a search without query param to display results as: [http://www.discogs.com/search/](http://www.discogs.com/search/)

Thanks.

**Comment by bartve** [comment]
I don't think it's possible to specifically search for a format like "vinyl" or "CD", see the API docs: http://www.discogs.com/developers/#page:database,header:database-search 

However, `disconnect` always added the `q=` param, which according to the API docs is optional and can be omitted. You can now provide an empty (`null, Undefined, ""`) search param to `database().search()` and the `q=` param won't be added to the API call.
