### ISSUE TITLE
Missing referenced dependencies

### ISSUE THREAD

**Issue by jhabdas** [bartve/disconnect#23]
Thanks for putting this together. I arrived here from a link in the Discogs API documentation.

While testing things out I noticed some of this project's library files reference node modules which are not listed in the `package.json` dependency manifest. Examples include `querystring` in `lib/util.js`, and `https` and `zlib` in `lib/client.js`.

I tried installing the missing dependencies manually but got hung up on a [`node-waf` error](https://github.com/kkaefer/DEPRECATED-node-zlib/issues/14) installing `zlib`, which is currently  deprecated yet required by this project.

Any pointers?

**Comment by bartve** [comment]
They are Node JS core modules that don't require any additional reference in package.json. See:
https://nodejs.org/dist/latest-v6.x/docs/api/https.html
https://nodejs.org/dist/latest-v6.x/docs/api/zlib.html
https://nodejs.org/dist/latest-v6.x/docs/api/querystring.html
etc.

I haven't really tested with the latest Node releases though, I might have some time for this tomorrow.

**Comment by jhabdas** [comment]
Thanks for the info. I'm on Node 6.x and NPM 3, so I'll give it another shot. It would be helpful to see the supported engines specified in the package manifest or a link to a Travis build so I could emulate a known working environment. But I'll take your word for it.

**Comment by bartve** [comment]
Well, supported engines are in `package.json`:

```
"engines": {
    "node": ">= 0.10.0"
}
```
But I wrote that before the big version jump. I have tested with later versions > 1, but not with the latest one I have to admit.
