### ISSUE TITLE
Search not working with Promise

### ISSUE THREAD

**Issue by lauritzsh** [bartve/disconnect#27]
Hey, great library. Nice with automatic rate limiting.

Database searching with Promise is not working for me however. For example

```javascript
db.search('skrillex', { type: 'label' }, (err, res) => {
  console.log(res);
})
```

is returning just five items like their own API with `https://api.discogs.com/database/search?q=skrillex&type=label&token=[redacted]`. However if I am using a Promise like

```javascript
db.search('skrillex', { type: 'label' })
  .then(console.log)
```

I get 870 items with all sorts of different results. Basically everything with Skrillex I assume.

Should it instead of [this](https://github.com/bartve/disconnect/blob/2a8853c159b1d62b2750faea7736cd885df04fd0/lib/database.js#L164-L168)

```javascript
if(arguments.length <= 2){
	if(typeof params === 'function'){ callback = params; } // No extra search params, the callback is the second function param
}else{
	obj = params;
}
```

just be a simple `&&` check

```javascript
if(arguments.length <= 2 && typeof params === 'function'){
	callback = params; // No extra search params, the callback is the second function param
}else{
	obj = params;
}
```

since the length is `<= 2` but params is not a function, `obj` should just be set to `params`. I will create a pull request for you, just checking first that the logic is sound.

**Comment by bartve** [comment]
It's slightly more subtle. This way `obj` will end up being `undefined` when you just add 1 param. Will add a fix today. Thanks for reporting!

**Comment by lauritzsh** [comment]
That's true, good catch. I see you have fixed it, very nice! Thank you.
