### ISSUE TITLE
new entry in my discogs setting: Authorized Applications on every /authorize

### ISSUE THREAD

**Issue by thomaswiedmann** [bartve/disconnect#33]
Question, need help.

On every new and correct /authorize I get a new entry in my discogs setting: Authorized Applications. Test three times, get three entries in my Authorized Applications. Is this normal?

**Comment by bartve** [comment]
I'm no OAuth expert, but it seems normal to me as each time you do a new /authorize you get granted a new access key from Discogs while the previous one is still valid.

**Comment by thomaswiedmann** [comment]
To revoke my "Authorized Applications" I have to [revoke] it using my User/Settings/appications form?

The token from /authorize is here use as access_key
Revoke my Application in my settings/applications. The form POST something like his to remove:
https://www.discogs.com/oauth/revoke?access_key=lkZzRqeVAtqwZrdJEULWNlWKrGaJdvxOicpjJVCb

Is there any API way to do this?

**Comment by bartve** [comment]
No API way as far as I know.

**Comment by thomaswiedmann** [comment]
Thanks. Hope discogs will add something like that in the future.
