### ISSUE TITLE
database.search not working when query is ommited and params object is passed

### ISSUE THREAD

**Issue by pedro-otero** [bartve/disconnect#38]
I came across this issue when trying to perform this search:

`/database/search?artist=Lana Del Rey&title=Honeymoon&type=master`

There is no query parameter. This search runs ok with an http client returning 2 results. So I invoke the search function like this:

```javascript
db.search({artist: 'Lana Del Rey', title: 'Honeymoon', type: 'master'})
```
And disconnect ignores my params object altogether. In the response I get `pagination.urls.last` is `https://api.discogs.com/database/search?q=&per_page=50&page=1000`.

**Comment by bartve** [comment]
Thanks for reporting and fixing! Will take a look at this next Thursday, I'll have some time then.

**Comment by bartve** [comment]
Oops, will merge next week. Busy times.
