### ISSUE TITLE
Support for browsers

### ISSUE THREAD

**Issue by anatoliyarkhipov** [bartve/disconnect#40]
Hi! Do I understand correctly that the lib works only in NodeJS environment at the moment? 

As I can see there are three NodeJS modules used:
- `https`
- `zlib`
- `url`

## `https`

`https` is used in the [`client.js`](https://github.com/bartve/disconnect/blob/es6/lib/client.js). The only method is needed is `request`. It should be easy to replace it with a cross-platform lib.

## `zlib`

I'm not sure is it possible to implement its functional in browser at all?

## `url`

If I correctly understand it's already implemented: 
https://www.npmjs.com/package/url

**Comment by bartve** [comment]
Yes, `disconnect` is currently only for NodeJS and I have no plans to port it to browser. I personally see no valid use-case for it and it would require some serious re-writing as the https and zlib dependencies are already handled by your browser.

**Comment by anatoliyarkhipov** [comment]
Thanks for the response @bartve!

A few days after posting the issue I also figured out that there is no use-case for `disconnect` in the browser.
