### ISSUE TITLE
Get image error

### ISSUE THREAD

**Issue by silveur** [bartve/disconnect#41]
Getting images through the getImage function doesn't work anymore and returns the following:

{ DiscogsError
    at IncomingMessage.passData (/Users/silvereletellier/dev/ChezEmile/node_modules/disconnect/lib/client.js:212:23)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9) statusCode: 500, message: 'Unknown error.' } 

'\n<html>\n<head>\n<title>Fastly error: unknown domain api.discogs.com</title>\n</head>\n<body>\n

Fastly error: unknown domain: api.discogs.com. Please check that this domain has been added to a service.</body></html>'

Furthermore when I try and download an image with the request module I get the following http response:

503 - Service Unavailable

Any idea?

**Comment by bartve** [comment]
Does https://api.discogs.com/ resolve in the browser for you?

**Comment by silveur** [comment]
It does resolve for me yeah... no idea about oAuth but that doesnt sound good neither.
Will post on the discogs forum and see whats up

**Comment by silveur** [comment]
Hi @bartve so they seem to have changed the url from api-img.discogs.com to img.discogs.com (without notice) which is fine but then downloading from Disconnect doesn't work anymore.
Furthermore when I request/download an image from a Nodejs app I have a 503 Service Unavailable response but it works in the browser... 
Do you have an idea the reason for this? It also works with Curl somehow...

```
curl -vvv https://img.discogs.com/sxp9nEjC-c5WYsiQ9liFMOYJJZw\=/fit-in/150x150/filters:strip_icc\(\):format\(jpeg\):mode_rgb\(\):quality\(40\)/discogs-images/R-8419142-1468234937-8283.jpeg.jpg > image.jpg
```

**Comment by bartve** [comment]
Quick fix: On line 161 replace `Host': this.config.host,` with `'Host': urlParts.host || this.config.host,`

I hope to be able to release this to npm soon. Not much time at the moment.

**Comment by bartve** [comment]
Managed to squeeze a release in. Should be fixed now.
