### ISSUE TITLE
Empty images uri

### ISSUE THREAD

**Issue by remimarsal** [bartve/disconnect#42]
Hi Bart!

As written in the README, image URLs require auth.
> Image requests themselves don't require authentication, but obtaining the image URLs through, for example, release data does.

However it is not clearly specified which type of auth. Providing a key and a secret while instanciating Disconnect does not seem to be enough as images URLs are always empty.

I tried setting the Authentication header via curl as well and same result.

Is it really mandatory to setup OAuth to get images URLs or am I doing something wrong ?

Thanks!

**Comment by bartve** [comment]
> Providing a key and a secret while instanciating Disconnect does not seem to be enough as images URLs are always empty.

You need to provide your user token then. Key/secret are for OAuth calls. 
See https://github.com/bartve/disconnect#discogs-auth

**Comment by remimarsal** [comment]
@bartve I guess it was just some sort of API hiccup since I'm now getting them properly with just Key/secret. Thanks anyway, closing this! ;)
