### ISSUE TITLE
Getting Next Page Of Search?

### ISSUE THREAD

**Issue by MonkRocker** [bartve/disconnect#49]
I see that search calls are returning the pagination object from Discogs, but since the search call doesn't let me specify a page to return, what's the correct way to page through results?

Thanks!

**Comment by bartve** [comment]
Discogs API says search accepts pagination https://www.discogs.com/developers/#page:database,header:database-search so just add them in the params when doing a search call.

**Comment by MonkRocker** [comment]
Ah my bad.  Didn't see that.  Thanks!
