### ISSUE TITLE
sorting releases from marketplace

### ISSUE THREAD

**Issue by Shnass** [bartve/disconnect#51]
I can't see the examples of using the marketplace. I'm trying to get only the recently added records from the store, is it possible?

**Comment by bartve** [comment]
You can set sorting params for a marketplace inventory:
https://www.discogs.com/developers/#page:marketplace,header:marketplace-inventory

So that would result into something like this to show the 10 most recent listings for user 'USER_NAME' (not tested!):
```javascript
var marketplace = new Discogs().marketplace();
var params = {sort: 'listed', sort_order: 'desc', page: 1, per_page: 10};
marketplace.getInventory('USER_NAME', params, function(err, data){
    console.log(data);
});
```
