### ISSUE TITLE
Problem with Client().database().getRelease()

### ISSUE THREAD

**Issue by jeromefaria** [bartve/disconnect#53]
Hi!

I have recently started to get multiple errors of type `UnhandledPromiseRejectionWarning` while using `Problem with Client().database().getRelease()`, even though I do have a catch block in place in my code.

This is the error:

```js
(node:43691) UnhandledPromiseRejectionWarning: DiscogsError: Unknown error.
    at IncomingMessage.passData (/<path-to-my-project>/node_modules/disconnect/lib/client.js:212:23)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:43691) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

And this is my code:

```js
public getRelease({ id }): Promise<any> {
  return new Promise((resolve, reject) => {
    const db = new Client(this.token).database();

    db.getRelease(id)
      .then(response => resolve(response))
      .catch(error => reject(error));
  });
}
```

Am I doing something wrong? This has been working for months, it's only recently that I started to get this error ocasionally.

Thank you!

**Comment by jeromefaria** [comment]
Actually, I was missing a `catch()` on my top function, and now I was able to identify the error as follows:

```js
{ DiscogsError: Unknown error.
    at IncomingMessage.passData (/Users/jeromefaria/Work/dscgrm/node_modules/disconnect/lib/client.js:212:23)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) statusCode: 502, message: 'Unknown error.' }
```

Apparently, Discogs is occasionally throwing a `502` for unknown reasons.

**Comment by michaelck** [comment]
@jeromefaria - I'm glad I saw your post, as I'm also getting a lot of `502` errors and couldn't make sense of it since nothing has changed in my script. Is this a known issue / is there a thread you can point me towards? 

Thanks!

**Comment by michaelck** [comment]
@jeromefaria, you may be interested in this update. I've heard back from Discogs staff regarding recent uptick in `502`s. Although, they didn't share details they told me that they were aware of the issue over the last few days, but that things should have stabilized as of this afternoon.

[Thread on Discogs](https://www.discogs.com/forum/thread/789913?page=1#7841761)

**Comment by jeromefaria** [comment]
Thanks, @michaelck! It does seem to have stabilised in the last few days; at least I didn't notice that problem anymore.

Closing this as it appears to have been an issue on Discogs' side all along.
